### ISSUE TITLE
rpi performace

### ISSUE THREAD

**Issue by natxopedreira** [kutayyildiz/facelib#1]
Hello

I tried your library on a rpi3 with Buster and usb coral accelerator. After a nightmare trying to install, related to scikit-image installation i was able to make it work.

But i was surprise to see that it need 0.5sec to process a 320x240 image with just a clean example, nothing fancy. Are you sure its using edgeTPU??

I looked at the code and seems using tf_lite but not edgetpu acceleration

`from tflite_runtime.interpreter import Interpreter, load_delegate`

Is that performance expected? maybe im using a old version or something?

Thanks!

**Comment by kutayyildiz** [comment]
You are right, 0.5s is too high for tpu inference.
Did you use the tpu version of face_detector & landmark_detector & feature_extractor?
If not try the following code.
```python
face_detector = facerec.SSDFaceDetector(tpu=True)
landmark_detector = facerec.LandmarkDetector(name="mobilenet_int8_tpu")
feature_extractor = facerec.FeatureExtractor(name="mobilenet_int8_tpu")
pipeline = facerec.Pipeline(face_detector, landmark_detector, feature_extractor)
bboxes, landmarks, features = pipeline.predict(some_image_array)
```
Link to available models;
[feature extractor models](https://github.com/kutayyildiz/facelib/tree/master/facelib/facerec/feature_extraction/data)
[landmark detection models](https://github.com/kutayyildiz/facelib/tree/master/facelib/facerec/landmark_detection/data)
If there still is no improvement on inference, can you share the code please?

**Comment by natxopedreira** [comment]
Thanks for your reply!!!!, yes is very slow...

Just tried exactly your code and get 0.63 first time i executed and 0.56 after that once the model is loaded
[https://gist.github.com/natxopedreira/0cb99433eaf85f0834bd73e5aad12e3d](https://gist.github.com/natxopedreira/0cb99433eaf85f0834bd73e5aad12e3d)

I know usb accelerator is correctly installed as im able to run google coral examples

**Comment by natxopedreira** [comment]
Hello

I think the problem comes from another point, i run a test sample code and im getting abnormal speed, very slow, i posted a issue on tflite repo

[https://github.com/google-coral/tflite/issues/18
](https://github.com/google-coral/tflite/issues/18
)

**Comment by kutayyildiz** [comment]
I run the code you linked on rpi4.
Inference speed is 0.085s on a very crowded image. Note that multiple executions resulted on different inference speeds(0.075s-0.095s). I recommend you to use [timeit](https://docs.python.org/3/library/timeit.html) module for more accurate results.

Please have a look at the [inference speeds](https://github.com/kutayyildiz/facelib/blob/master/facelib/_benchmark/performance_face_detection.csv) i tested on rpi3b+ and rpi4.

- ARM Cortex-A72 = rpi4
- ARM Cortex-A53 = rpi3b+

As seen on the tests, rpi4 which has usb3 performs ~3 times better compared to rpi3b+ which has usb2.
The [issue](https://github.com/google-coral/tflite/issues/18) you posted has the similar issue i believe. The example [here](https://github.com/google-coral/tflite/tree/master/python/examples/detection) may be using dev board, which has usb3 and integrated tpu.

**Comment by kutayyildiz** [comment]
Also, could you please run the same code without tpu inference, and post the inference speed?
```python
face_detector = facerec.SSDFaceDetector(tpu=False)
landmark_detector = facerec.LandmarkDetector(name="mobilenet_int8_cpu")
feature_extractor = facerec.FeatureExtractor(name="mobilenet_int8_cpu")
pipeline = facerec.Pipeline(face_detector, landmark_detector, feature_extractor)
```

**Comment by natxopedreira** [comment]
I understand your point and sure rpi4 will be faster.

What surprise me is the fact that im using a intel neural stick with opencv inference on the same raspberry and im able to get 20 fps using 3 models processing a 320x240 video

I will try without tpu to see the difference

**Comment by natxopedreira** [comment]
Running without tpu i get 1.5s

**Comment by kutayyildiz** [comment]
Thanks for your reply! I just wanted to know if you are utilizing the TPU or not.
Note that input frame size is resized to the models input size, so it does not effect the speed. 

I think OpenCVs face detector uses a different model. The model i used is [facessd_mobilenet_v2_quantized_open_image_v4](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). Additively, the landmark detector and face feature extractor this library is using are all CNN models. If the model you are using on OpenCV is a ligther model it may dramatically effect the performance.

But still, 10x performance difference is huge.

**Comment by natxopedreira** [comment]
I can use those models
[https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/3/](https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/3/)

Depending on how "heavy" is the model fps goes from 10 lowest to 20 fastest with the 3 models and in async mode.

But i think difference with coral board is too much, im installing on a clean Buster system to see if  i had something weird on my install

**Comment by natxopedreira** [comment]
Im able to reproduce the abnormal speed on a fresh sd card so must be something that is not in my install, if you are curious discussion can be followed on [https://github.com/google-coral/edgetpu/issues](https://github.com/google-coral/edgetpu/issues)

**Comment by natxopedreira** [comment]
I will close this as is dependent on rpi3b, library works perfect
